"""Module containing constants."""

# CSV field names.
COUNT_FIELDNAME = 'count'
FILENAME_FIELDNAME = 'filename'
LABEL_FIELDNAME = 'label'
NGRAM_FIELDNAME = 'ngram'
SIZE_FIELDNAME = 'size'
TOTAL_FIELDNAME = 'total'

QUERY_FIELDNAMES = [NGRAM_FIELDNAME, SIZE_FIELDNAME, FILENAME_FIELDNAME,
                    COUNT_FIELDNAME, LABEL_FIELDNAME]
COUNTS_FIELDNAMES = [FILENAME_FIELDNAME, SIZE_FIELDNAME, TOTAL_FIELDNAME,
                     COUNT_FIELDNAME, LABEL_FIELDNAME]
